#!/usr/bin/python

from sys import argv
import os

if len(argv) < 2:
    print('usage: lexb file.lexb')
    exit(1)

if not argv[1].endswith('.lexb'):
    print('usage: lexb file.lexb')
    exit(1)

with open(argv[1],'r') as fl:
    if os.path.exists(argv[1]) == False:
        print('file doesn\'t exists')
        exit(1)
    fl = fl.readlines()
    for i in fl:
        if i.startswith('//'):
            i = ''
        for w in i.split():
            if w == 'print:':
                w = ''
            elif w == 'endl':
                print()
            else:
                print(w,end=' ')
