#!/usr/bin/python

from sys import argv
import os

if len(argv) < 2:
    print('usage: lexb file.lexb')
    exit(1)

if not argv[1].endswith('.lexb'):
    print('usage: lexb file.lexb')
    exit(1)

with open(argv[1],'r') as fl:
    if os.path.exists(argv[1]) == False:
        print('file doesn\'t exist')
        exit(1)
    fl = fl.readlines()
    with open('lexb.c','w') as wf:
        wf.write('#include <stdio.h>\n')
        wf.write('int main() {\n')
        for i in fl:
            if i.startswith('@'):
                i = ''
            for w in i.split():
                if w == 'print:':
                    wf.write('printf("')
                elif (w == 'endl') or (w == 'pend'):
                    wf.write('\\n");\n')
                else:
                    wf.write(f'{w} ')
        wf.write('return 0;\n');
        wf.write('}\n')
